[options]
colorscheme = "gruvbox"
colorscheme_bg = "dark"
enable_guicolors = true
statusline_separator = "nil"
statusline_inactive_separator = "bar"
buffer_index_type = 4
windows_index_type = 3
enable_tabline_filetype_icon = false
enable_statusline_mode = false
statusline_unicode_symbols = false
vimcompatible = false
filemanager = "defx"

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "VersionControl"

[[layers]]
name = "colorscheme"

[[layers]]
name = "leaderf"

[[layers]]
name = "tmux"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#latex"

[[layers]]
name = "lang#r"

[[layers]]
name = "lang#scala"

[[layers]]
name = "lang#extra"

[[layers]]
name = "format"

[[layers]]
name = 'checkers'
show_cursor_error = true
[layer.clang_std]
c = "c11"
cpp = "c++1z"
objc = "c11"
objcpp = "c++1z"

[[layers]]
name = "lsp"
filetypes = [
    "java",
    "rust",
    "python",
    "c",
    "cpp"
]
[layers.override_cmd]
c = ["clangd", "--limit-results=5"]
cpp = ["clangd", "--limit-results=5"]
## JDT: https://download.eclipse.org/jdtls/snapshots/?d
java = [  
    "java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx1G",
    "-jar",
    "/home/chenxm/.local/lib/jdt-language-server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar",
    "-configuration",
    "/home/chenxm/.local/lib/jdt-language-server/config_linux",
    "-data",
    "/home/chenxm/.cache/javalsp"
]

[[custom_plugins]]
name = "mcmire/vim-grakn"
merged = false
